# Generated by Django 4.2.3 on 2023-08-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.CharField(max_length=200, verbose_name='ID пользователя telegram'),
        ),
    ]
