# Generated by Django 4.2.3 on 2023-07-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postfavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfavorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
